- backend/app/main.py
- frontend/lib/gptchat.dart
- frontend/pubspec.yaml
들여쓰기라던가 오타라던가 수정했습니다
드디어 프론트랑 백이 연동이 된다
<br>
> fix: 자질구레 버그 수정

- backend/app/api/routers/disease_prediction_router.py
- backend/app/api/schemas/disease_prediction_session.py
- backend/app/api/schemas/primary_disease_prediction.py
- backend/app/core/config.py
- backend/app/main.py
- backend/app/services/firebase_service.py
- backend/app/services/gpt_service.py
- backend/app/tests/test_utils.py
- backend/app/utils/data_processing.py
1차 응답까지에 해당하는 DB 저장 기능 구현했습니다
Session에 모든 정보를 모아서 한번에 저장되도록 하였습니다.
데모를 위한 DB 적용
<br>
<br>
2차 응답까지 구현하는거랑, 사용자 정보 저장 구현해야합니다
<br>
> feat: DB 저장 기능 구현

- frontend/lib/gptchat.dart
- frontend/lib/home_page.dart
- frontend/lib/widgets/select_card.dart
그리드뷰(선지) 크기 및 글씨 배치 조정, 결과 버튼 연결하는 틀 구성.
<br>
백과 합쳐봐야 알 듯 함.
<br>
머지할 땐 없음. 추후에 스페이스바랑 엔터 입력 시 멈춤.
<br>
<br>
결과 버튼과 증상 선택 한 게 백으로 넘어가는 걸 연결. 결과 카드 구현. (데모까지)
결과 화면에 진료과를 API랑 연동시켜서 표시. (최종까지)
<br>
> feat : 자잘자잘 UI 수정

- frontend/lib/gptchat.dart
- frontend/lib/widgets/select_card.dart
증상 선택 해서 백으로 넘어가도록 해야했음. 최종 결과 버튼 연결이 필요했음.
머지 해봐야.,... 알 수 있을 듯 함.
연동..
일단 머지가 잘 되는지 확인 필요. 선지 선택이 제대로 넘어가는가, 그 선지의 결과가 제대로 넘어와 결과 버튼으로 출력이 되는가 확인 필요.
최종까진 진료과를 API랑 연동시켜서 표시 및 저장 목록 불러오기.
> feat : 선지 선택 결과 백에 전송 및 결과 버튼 연결 구현

- frontend/lib/gptchat.dart
- frontend/lib/main.dart
- frontend/lib/widgets/result_card.dart
- frontend/lib/widgets/select_card.dart
selectCard 크기와 배치, 글자 굵기와 배치 수정 및 resultCard 내용 수정
<br>
없음.
<br>
UI 혹시 고치고 싶은 부분이 있는지
<br>
<br>
최종까지 저장된 이전 결과 목록, 진료과-지도 연결 등
<br>
> feat : 최종(아마) UI 수정

- backend/app/api/routers/disease_prediction_router.py
- backend/app/api/schemas/disease_prediction_session.py
- backend/app/main.py
- backend/app/services/firebase_service.py
- backend/app/services/gpt_service.py
- backend/app/utils/api_client.py
- backend/app/utils/data_processing.py
> fix: 백엔드 경로 수정

- backend/app/main.py
-내용은 여기에-   
<br>
-내용은 여기에-   
<br>
-내용은 여기에-   
<br>
-내용은 여기에-   
<br>
-내용은 여기에-   
<br>
> fix:cert json 환경변수 구조 변경

- backend/app/main.py
- frontend/lib/gptchat.dart
> fix: 프론트 경로 수정

- frontend/lib/gptchat.dart
- frontend/lib/widgets/chatgpt.dart
- frontend/lib/widgets/popup.dart
필요없는 변수 등 삭제, 구조 변경, 공백 및 시도여부 팝업메시지 추가.
필요없는 부분 삭제. 코드 가독성 증가 위함.
<br>
공백을 입력했는데 선지가 나오는데 확인 필요.
<br>
추가로 필요한 부분.
<br>
<br>
진단 받아보기 버튼을 눌렀을 때 결과 생성 중이라는 팝업.
new chat 로직.
log out 연동.
결과 리스트.
etc...
<br>
> feat : gptchat.dart refactoring, popup

- backend/app/api/routers/disease_prediction_router.py
- backend/app/main.py
- frontend/build/web/flutter_bootstrap.js
- frontend/build/web/flutter_service_worker.js
- frontend/build/web/index.html
- frontend/build/web/main.dart.js
- frontend/lib/gptchat.dart
> fix: update API

- backend/app/api/routers/user_router.py
- backend/app/api/schemas/disease_prediction_session.py
- backend/app/api/schemas/user.py
- backend/app/services/session_service.py
> feat: user 정보 가져오기 기능 추가

- backend/app/api/exceptions/general_exception_handler.py
- backend/app/core/logging_config.py
- backend/app/core/middlewares.py
- backend/app/main.py
> feat: 로깅 기능 추가

- backend/app/api/schemas/primary_disease_prediction.py
- backend/app/api/schemas/secondary_disease_prediction.py
- backend/app/core/prompt.py
- backend/app/services/gpt_service.py
- backend/app/utils/api_client.py
- backend/app/utils/data_processing.py
응답 생성 안정성을 위한 Function Calling 기능을 추가하여 답변을 json 형태로 받았습니다.
<br>
> feat: Function Calling 기능 추가

- backend/app/api/routers/user_router.py
> fix: api 수정

- frontend/lib/login_page.dart
- frontend/lib/signUp_page.dart
로그인 및 회원가입 url 에 /api 추가
<br>
없음 
<br>
없음
<br>
<br>
<br>
> chore: 로그인 api 약간의 수정

- frontend/lib/home_page.dart
- frontend/lib/login_page.dart
- frontend/lib/signUp_page.dart
- frontend/pubspec.yaml
chore: 로그인 컨트롤러 추가 및 디자인 변경
<br>
없음
<br>
로그인 입력 처리 추가했습니다
<br>
-내용은 여기에-   
<br>
-내용은 여기에-   
<br>
> chore: 로그인 컨트롤러 추가 및 디자인 변경

- frontend/lib/login_page.dart
feat: 로그인 구현 완료
<br>
없습니다
<br>
없습니다 
<br>
-내용은 여기에-   
<br>
-내용은 여기에-   
<br>
> feat: 로그인 구현 완료

- frontend/lib/gptchat.dart
로그인 시 유저 토큰을 넘겨주도록 api 수정.
사용자가 서비스 이용이 끝난 후 새로운 채팅을 이용할 수 있도록 함.
로그아웃 구현으로 토큰을 프론트에서 버리도록.
<br>
아직 없음.
<br>
없으므로 바로 머지하겠음.
<br>
<br>
결과로 도출된 진료과를 바탕으로 구글맵과 연동시켜 보여주기 (주변 병원과 3차 병원 여부)
유저가 이용했던 채팅 결과 목록 구현
<br>
> feat : newChat, Logout 작동 확인

- backend/app/services/disease_prediction_service.py
- backend/app/services/session_service.py
-내용은 여기에-   
오류처리 메세지 출력 용이하게 하기 위해 오류 메세지를 한글명으로 변경하였습니다.
> feat: 한글명으로 오류메세지 변경

- backend/app/services/disease_prediction_service.py
> fix: 스키마 재수정

- frontend/lib/authentication.dart
- frontend/lib/gptchat.dart
- frontend/lib/login_page.dart
- frontend/lib/result_list_class.dart
- frontend/lib/widgets/result_list_detail.dart
- frontend/pubspec.yaml
shared_preference가 보안상 안 좋다고 함. 사용자 토큰이라 flutter_secure_storage 방식이 나을 것으로 판단.
<br>
새로고침이나 뒤로가기를 눌러도 로그인이 유지되도록..!
목록에서 예전 기록 선택 시 세부 사항 UI 구현.
<br>
> feat : shared_preference에서 flutter_secure_storage로 token 방식 변경.

- frontend/lib/google_map.dart
구글맵 UI 변경하여 상세정보 잘 뜸
<br>
없음 
<br>
없음
<br>
<br>
백과의 추가 연동, gpt_chat 버튼과의 연동
<br>
> ci: 구글맵 UI 변경 완료

- frontend/lib/google_map.dart
- frontend/web/index.html
구글맵 코드, 병원 api 연동 완전 완료했습니다
<br>
없음
<br>
없음
<br>
<br>
gpt_chat.dart와의 연결, 및 변수 전송
<br>
> feat: 구글맵 병원api연동 완료

- frontend/lib/google_map.dart
근처 병원이 없는 경우, 콘솔 외 화면에 문구를 띄어줍니다  
<br>
없습니다
<br>
없습니다
<br>
없습니당
<br>
> feat: 근처 병원 예외처리
